apiVersion: v2
description: Inspector
name: inspector
type: application
version: 0.0.2
appVersion: 0.0.1
dependencies:
  - name: redis
    version: 10.5.7
    repository: https://charts.helm.sh/stable
  - name: postgresql
    version: 8.6.3
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
