docker:
  image: ms32035/inspector
  tag: master


environment:
  REDIS_URL: redis://inspector-redis-master:6379/0

inspector:
  django:
    adminUrl: admin
    collectFastStrategy: collectfast.strategies.filesystem.FileSystemStrategy
    settingsModule: config.settings.production
    ssl:
      redirect: False
    secretKey: 966212301e1bb593c31503b627e0d05355287c2da620bac98c7603cdc49729a4
    fieldEncryptionKey: Ms096q5p7OoVLKPWy69et0JSoPNJacb98VvIZ7pdxYY=

  nodeSelector: {}
  resources: {}

flower:
  nodeSelector: {}
  resources: {}
  user: inspector
  password: inspector

worker:
  replicas: 1
  nodeSelector: {}
  resources: {}

beat:
  nodeSelector: {}
  resources: {}

ingress:
  inspector:
    path: ""
    annotations: {}
  flower:
    path: ""
    annotations: {}

redis:
  usePassword: false
  master:
    persistence:
      enabled: false
  cluster:
    enabled: false
    slaveCount: 0

postgresql:
  enabled: true
  postgresqlUsername: inspector
  postgresqlDatabase: inspector
  postgresqlPassword: inspector

  service:
    port: 5432
