apiVersion: v1
kind: Service
metadata:
  name: "{{ template "inspector.name" . }}-flower"
  labels:
    app: {{ template "inspector.name" . }}
    component: flower
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "inspector.name" . }}
    component: inspector-flower
    release: {{ .Release.Name }}
  ports:
  - name: flower
    protocol: TCP
    port: 5555
    targetPort: 5555
status:
  loadBalancer: {}
