apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "inspector.name" . }}-flower"
  labels:
    app: {{ template "inspector.name" . }}
    component: "{{ template "inspector.name" . }}-flower"
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        checksum/inspector-configmap: {{ include (print $.Template.BasePath "/inspector-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "inspector.name" . }}
        component: "{{ template "inspector.name" . }}-flower"
        release: {{ .Release.Name }}
    spec:
      containers:
      - args:
        - /start-flower
        envFrom:
          - configMapRef:
              name: "{{ template "inspector.name" . }}-env"
        image: {{ .Values.image }}
        imagePullPolicy: Always
        name: "{{ template "inspector.name" . }}-flower"
        ports:
        - name: flower
          containerPort: 5555
          protocol: TCP
        resources:
{{ toYaml .Values.flower.resources | indent 10 }}
      restartPolicy: Always
      {{- if .Values.flower.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.flower.nodeSelector | indent 8 }}
      {{- end }}
status: {}
