apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: inspector-flower
  labels:
    app: {{ template "inspector.name" . }}
    component: "{{ template "inspector.name" . }}-flower"
    release: {{ .Release.Name }}
  annotations:
    {{ range $key, $value := .Values.ingress.flower.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.flower.path }}
            backend:
              serviceName: inspector-flower
              servicePort: flower
      host: {{ .Values.ingress.flower.host }}
